name: linux

on: [push, pull_request]

jobs:
    build:
        strategy:
            matrix:
                cxx: [g++-12, clang++-14]
                build_type: [Debug, Release]

        runs-on: ubuntu-22.04

        steps:
        - uses: actions/checkout@v3
          with:
            submodules: recursive

        - name: Install Dependencies
          run: |
                sudo apt update
                sudo apt install -y libsdl2-dev libassimp-dev

        - name: Create Build Environment
          run: cmake -E make_directory ${{github.workspace}}/build

        - name: Configure
          shell: bash
          working-directory: ${{github.workspace}}/build
          env:
                CXX: ${{matrix.cxx}}
          run: cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} $GITHUB_WORKSPACE

        - name: Build
          shell: bash
          working-directory: ${{github.workspace}}/build
          run: time cmake --build . --config ${{matrix.build_type}}

        - name: Build
          shell: bash
          working-directory: ${{github.workspace}}
          run: doxygen docs/doxygen.ini

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          if: github.ref == 'refs/heads/main' && (success())
          with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./build/docs/html/