name: windows

on: [push, pull_request]

jobs:
    build:
        strategy:
            matrix:
                build_type: [Debug, Release]
        runs-on: windows-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: Configure CMake
              run: cmake -S . -B build

            - name: Build
              run: cmake --build build --config ${{ matrix.build_type }}

