name: windows

on: [push, pull_request]

jobs:
    build:
        strategy:
            matrix:
                build_type: [Debug, Release]
                blur_use_gauss: [ON, OFF]
        runs-on: windows-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: Configure CMake
              run: cmake -S . -B build -DBLUR_USE_GAUSS=${{ matrix.blur_use_gauss }}

            - name: Build
              run: cmake --build build --config ${{ matrix.build_type }}

